---
version: '3'
services:
  pulumi:
    build:
      context: .
      args:
        - PULIMI_UID="${UID}"
        - PULUMI_CONFIG_PASSPHRASE=dev
    volumes:
      - .pulumi:/home/pulumi/.pulumi
      - .:/home/pulumi/app
    env_file:
      - .env
